# Thname: Dependency Security Scan
name: Weekly Project Report

on:
  schedule:
    # Runs at 9:00 AM on Monday every week
    - cron: '0 9 * * 1'

jobs:
  generate_report:
    runs-on: ubuntu-latest
    steps:
      - name: Get Issues and Pull Requests
        id: report
        run: |
          echo "Open Issues: $(curl -s 'https://api.github.com/repos/${{ github.repository }}/issues?state=open' | jq 'length')" >> $GITHUB_STEP_SUMMARY
          echo "Open Pull Requests: $(curl -s 'https://api.github.com/repos/${{ github.repository }}/pulls?state=open' | jq 'length')" >> $GITHUB_STEP_SUMMARY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Send Report to Slack
        # Use a notification action here
on:
  schedule:
    # Runs at 12:00 AM on Monday every week
    - cron: '0 0 * * 1'

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run audit for vulnerabilities
        run: npm auditis is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
